project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "Open Research & Reproducibility"
  subtitle: "A practical guide for researchers"

  site-url: "https://terraetudo.github.io/open-research-reproducibility/"
  repo-url: "https://github.com/terraetudo/open-research-reproducibility"
  repo-actions: [edit, issue]

  page-navigation: true
  search: true
  favicon: cover.png

  sidebar:
    style: docked
    background: light
    title: "Open Research & Reproducibility"

  chapters:
    - index.qmd
    - 01-why-open.qmd
    - 02-fair-basics.qmd
    - 03-project-mgmt.qmd
    - 04-dmp.qmd
    - 05-organise-tidy.qmd
    - 06-docs-eln-sops.qmd
    - 07-code-quality-testing.qmd
    - 08-publishing-pids-reuse.qmd
    - 09-wrap-up-next-steps.qmd
    - resources.qmd
    - references.qmd

  navbar:
    right:
      - text: "Resources"
        href: resources.qmd
      - text: "References"
        href: references.qmd

  page-footer:
    left: "© UCL Great Ormond Street Institute of Child Health"
    right: "CC BY 4.0 · Built with Quarto"

format:
  html:
    theme: cosmo
    css: style.css
    number-sections: false
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-citations: true
    link-external-newwindow: true

bibliography: references.bib
csl: nature.csl